### ISSUE TITLE
stackstac.mosaic gives different results with different chunk sizes

### ISSUE THREAD

**Issue by robintw** [gjoseph92/stackstac#84]
I've got a strange issue with `stackstac.mosaic`, where I seem to get different results depending on the `chunksize` parameter that I give to the original `stackstac.stack` call.

I've stacked together a few tiles of elevation data, some of which overlap.

If I `stack` with a chunksize of 100, and then run `mosaic`, I get this output:

![image](https://user-images.githubusercontent.com/296686/140291960-064a8a6b-dd8b-4745-ab4b-e18bea4ec3d6.png)

But if I run the same thing with a chunksize of 1000, then I get this output:

![image](https://user-images.githubusercontent.com/296686/140291996-67f5c73f-005f-4274-a34a-b9dcd6c61722.png)

As you can see, there are some differences. We can show those more clearly if we subtract one from the other - which gives us this:

![image](https://user-images.githubusercontent.com/296686/140292113-857812ae-b6bb-470b-ac65-5beaa8b17a6e.png)

I'm rather confused by what is going on here: I don't think I'm doing something stupid in my code - but I wouldn't expect a change in the chunk size to change the result.

My full notebook is available [here](https://gist.github.com/robintw/0ec6c5a1227927eaefbea12f8e9c08e5), showing exactly what I'm doing. As you can see at the end of the notebook, doing a `max` over the time dimension works fine.

**Comment by robintw** [comment]
Just as an update to this, it seems to have something to do with no data values and masking. I have a load of values of zero which should really be NaN.

If I mask my `data` DataArray before mosaicing by doing:

```
d1000masked = data1000.where(data1000 != 0)
m1000 = stackstac.mosaic(d1000masked)
```

Then I get the same results for mosaicing with a chunk size of 100 and a chunk size of 1000.

This works ok as a work-around for the moment, but I think it still leaves the issue of getting different results with different chunk sizes - which is not what I would expect.

**Comment by gjoseph92** [comment]
@robintw looks like you figured it out. As the [`mosaic` docs](https://stackstac.readthedocs.io/en/latest/api/main/stackstac.mosaic.html) say:
> Flatten a dimension of a DataArray by picking the first non-NaN pixel.

The way `mosaic` currently tells if a pixel is valid or not is if it's NaN. Zero could be a perfectly valid value in many datasets, so the zeros in yours are treated as valid and are not replaced with the non-zero pixels "beneath" them.

As for why the results are different with different chunk sizes, this is also not too surprising. Depending on the chunk size, the grid formed by the chunks will overlap your data differently. If a chunk extends beyond the bounding-box of a file, the area outside the bounding-box will be filled with NaN (since that's the default `fill_value` for `stackstac.stack`). Then there are areas inside the bounding-box where the GeoTIFF contains zeros. You'd like these to be treated the same as NaNs, but they're not—they'll act as opaque to `mosaic` and cover up valid data beneath them, whereas NaN acts as transparent. So as you change the chunksize, where those transparent NaN areas are will change.

Now, stackstac will automatically mask out nodata values in the GeoTIFF (see the `fill_value` parameter in the [docs](https://stackstac.readthedocs.io/en/latest/api/main/stackstac.stack.html)). Clearly this is not happening. This makes me think your GeoTIFF files do not have a [`nodata` value or internal mask band](https://rasterio.readthedocs.io/en/latest/topics/masks.html#nodata-representations-in-raster-files) specified in their internal metadata. If you want things to work best, you should ensure your files set this.

If you can't or don't want to change the files themselves, then `data1000.where(data1000 != 0)` is the proper thing to do currently.

When I wrote stackstac, there was no way for STAC metadata to say what the nodata value was for an asset. Once [`raster:bands`](https://github.com/stac-extensions/raster) starts to be used, we should look at the `nodata` field there. In your case, your STAC catalog could specify nodata as 0, and stackstac would then automatically mask the zeros for you (even if the GeoTIFFs didn't specify a nodata value).

**Comment by robintw** [comment]
Thanks @gjoseph92 that makes sense - and thanks for the particularly prompt response too.
